# Generated by Django 5.2 on 2025-06-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_leakreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leakreport',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='leakreport',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leakreport',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leakreport',
            name='reported_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
