# Generated by Django 5.2 on 2025-06-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_leakreport_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leakreport',
            old_name='reported_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='leakreport',
            name='leak_type',
            field=models.CharField(choices=[('Pipe Burst', 'Pipe Burst'), ('Valve Failure', 'Valve Failure'), ('Illegal Connection', 'Illegal Connection'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
    ]
