# Generated by Django 5.2 on 2025-06-05 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroresearch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leak_type', models.CharField(choices=[('No Internet', 'Hakuna Intaneti'), ('Slow Connection', 'Muunganisho Mdogo'), ('Fiber Cable Cut', 'Kata Waya'), ('Password Change', 'Badilisha Neno Siri'), ('Router Malfunction', 'Routa Haifanyi Kazi'), ('Others', 'Nyingine')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
