# Generated by Django 5.2 on 2025-06-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroresearch', '0002_leakreport_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leakreport',
            name='leak_type',
            field=models.CharField(choices=[('Uvujaji kwenye bomba kuu', 'Main pipe leakage'), ('Uvujaji kwenye mita ya maji', 'Meter leakage'), ('pipe bursting', 'bomba limepasuka'), ('Uvujaji kutoka kwenye joint', 'Valve/joint leakage'), ('Others', 'Nyingine')], max_length=50),
        ),
    ]
